import { AFFECTATION_PERMISSIONS as P } from "./permissions"

export const AFFECTATION_GROUPS = {
  REFERENTIALS: [
    P.LIST_REGIONS,
    P.VIEW_REGION,
    P.CREATE_REGION,
    P.UPDATE_REGION,
    P.DISABLE_REGION,
    P.LIST_CENTERS,
    P.VIEW_CENTER,
    P.CREATE_CENTER,
    P.UPDATE_CENTER,
    P.DISABLE_CENTER,
    P.MAINTAIN_CENTER,
    P.ENABLE_CENTER,
    P.CHECK_CENTER_CAPACITY,
  ],
  REGIONS: [P.LIST_REGIONS, P.VIEW_REGION, P.CREATE_REGION, P.UPDATE_REGION, P.DISABLE_REGION],
  CENTERS: [P.LIST_CENTERS, P.VIEW_CENTER, P.CREATE_CENTER, P.UPDATE_CENTER, P.DISABLE_CENTER, P.MAINTAIN_CENTER, P.ENABLE_CENTER],
  REGIONAL_ASSIGNMENTS: [
    P.VIEW_REGIONAL_ASSIGNMENTS,
    P.PROPOSE_REGIONAL_ASSIGNMENT,
    P.ASSIGN_REGION,
    P.UPDATE_REGIONAL_ASSIGNMENT,
    P.VALIDATE_REGIONAL_ASSIGNMENT,
    P.CANCEL_REGIONAL_ASSIGNMENT,
  ],
  CENTER_ASSIGNMENTS: [
    P.VIEW_CENTER_ASSIGNMENTS,
    P.PROPOSE_CENTER_ASSIGNMENT,
    P.ASSIGN_CENTER,
    P.UPDATE_CENTER_ASSIGNMENT,
    P.VALIDATE_CENTER_ASSIGNMENT,
    P.CANCEL_CENTER_ASSIGNMENT,
  ],
} as const
