import { useEffect, useState } from "react"
import { accountsApi } from "../api"
import type { Actor } from "../types"
import { PageHeader, ErrorBox, Loading } from "../components"
import { getApiErrorMessage } from "@/api/api-error"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Link } from "react-router-dom"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function ProfilePage(){ const [a,setA]=useState<Actor|null>(null); const [e,setE]=useState(''); useEffect(()=>{accountsApi.profile().then(setA).catch(x=>setE(getApiErrorMessage(x)))},[]); if(e)return <ErrorBox message={e}/>; if(!a)return <Loading/>; return <><PageHeader title="Mon profil" description="Vos informations personnelles et professionnelles."/><div className="mb-6 flex flex-wrap gap-3"><Button render={<Link to="/app/profil/modifier"/>}>Modifier mon profil</Button><Button render={<Link to="/app/profil/mot-de-passe"/>} variant="outline">Changer mon mot de passe</Button></div><Card><CardContent className="grid gap-6 p-7 sm:grid-cols-2">{Object.entries({Nom:a.nom_complet,Identifiant:a.username,'Adresse e-mail':a.email,Téléphone:a.telephone||'Non renseigné',Titre:a.titre||'Non renseigné',Organisation:a.organisation||'Non renseignée',Statut:a.statut}).map(([k,v])=><div key={k}><p className="text-sm text-muted-foreground">{k}</p><p className="mt-1 font-semibold">{v}</p></div>)}</CardContent></Card></> }
export function EditProfilePage(){ const [form,setForm]=useState({first_name:'',last_name:'',telephone:'',titre:'',organisation:''}); const [msg,setMsg]=useState(''); const [err,setErr]=useState(''); useEffect(()=>{accountsApi.profile().then(a=>setForm({first_name:a.first_name,last_name:a.last_name,telephone:a.telephone||'',titre:a.titre,organisation:a.organisation}))},[]); const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v})); async function submit(e:React.FormEvent){e.preventDefault();setErr('');try{await accountsApi.updateProfile(form);setMsg('Profil modifié avec succès.')}catch(x){setErr(getApiErrorMessage(x))}} return <><PageHeader title="Modifier mon profil" backTo="/app/profil"/><Card><CardContent className="p-7"><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2">{[['first_name','Prénom'],['last_name','Nom'],['telephone','Téléphone'],['titre','Titre'],['organisation','Organisation']].map(([k,l])=><div key={k} className="space-y-2"><Label>{l}</Label><Input value={form[k as keyof typeof form]} onChange={e=>set(k,e.target.value)}/></div>)}<div className="sm:col-span-2">{err&&<ErrorBox message={err}/>} {msg&&<p className="mb-4 text-sm text-primary">{msg}</p>}<Button type="submit">Enregistrer</Button></div></form></CardContent></Card></> }
export function ChangePasswordPage(){ const [f,setF]=useState({ancien_mot_de_passe:'',nouveau_mot_de_passe:'',confirmation_mot_de_passe:''});const [m,setM]=useState('');const [e,setE]=useState(''); async function submit(x:React.FormEvent){x.preventDefault();setE('');try{await accountsApi.changePassword(f);setM('Mot de passe modifié avec succès.');setF({ancien_mot_de_passe:'',nouveau_mot_de_passe:'',confirmation_mot_de_passe:''})}catch(y){setE(getApiErrorMessage(y))}} return <><PageHeader title="Changer mon mot de passe"/><Card><CardContent className="max-w-2xl p-7"><form onSubmit={submit} className="space-y-5">{[['ancien_mot_de_passe','Ancien mot de passe'],['nouveau_mot_de_passe','Nouveau mot de passe'],['confirmation_mot_de_passe','Confirmer le mot de passe']].map(([k,l])=><div key={k} className="space-y-2"><Label>{l}</Label><Input type="password" value={f[k as keyof typeof f]} onChange={z=>setF(v=>({...v,[k]:z.target.value}))}/></div>)}{e&&<ErrorBox message={e}/>} {m&&<p className="text-sm text-primary">{m}</p>}<Button type="submit">Modifier le mot de passe</Button></form></CardContent></Card></> }
