/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from "react"
import { Link, useNavigate, useParams } from "react-router-dom"
import { accountsApi } from "../api"
import type { Actor, ActorAssignment, Delegation, Permission, PermissionRequest, Role } from "../types"
import { ACCOUNT_PERMISSIONS as P } from "../permissions"
import { EmptyState, Loading, PageHeader, PermissionGuard, StatusBadge } from "../components"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table"

export function PermissionRequestsListPage(){const[r,setR]=useState<PermissionRequest[]>([]);useEffect(()=>{accountsApi.permissionRequests().then(setR)},[]);return <><PageHeader title="Demandes d’accès" actionTo="/app/permissions/demandes/nouvelle" actionLabel="Demander un accès" actionPermission={P.REQUEST_PERMISSION}/>{r.length===0?<EmptyState message="Aucune demande."/>:<Card><Table><TableHeader><TableRow><TableHead>Demandeur</TableHead><TableHead>Autorisation</TableHead><TableHead>Date</TableHead><TableHead>Statut</TableHead><TableHead/></TableRow></TableHeader><TableBody>{r.map(x=><TableRow key={x.id}><TableCell>{x.acteur.nom_complet}</TableCell><TableCell>{x.permission.libelle}</TableCell><TableCell>{new Date(x.date_demande).toLocaleDateString('fr-FR')}</TableCell><TableCell><StatusBadge value={x.statut}/></TableCell><TableCell><Button render={<Link to={`/app/permissions/demandes/${x.id}`}/>} variant="outline" size="sm">Voir</Button></TableCell></TableRow>)}</TableBody></Table></Card>}</>}
export function PermissionRequestCreatePage(){const nav=useNavigate();const[p,setP]=useState<Permission[]>([]);const[a,setA]=useState<ActorAssignment[]>([]);const[f,setF]=useState({permission_id:'',affectation_acteur_id:'',justification:''});useEffect(()=>{accountsApi.permissions().then(setP);accountsApi.assignments().then(setA)},[]);async function submit(x:React.FormEvent){x.preventDefault();const d=await accountsApi.createPermissionRequest({permission_id:+f.permission_id,affectation_acteur_id:f.affectation_acteur_id?+f.affectation_acteur_id:null,justification:f.justification});nav(`/app/permissions/demandes/${d.id}`)}return <><PageHeader title="Nouvelle demande d’accès" backTo="/app/permissions/demandes"/><Card><CardContent className="p-7"><form onSubmit={submit} className="space-y-5"><Field label="Autorisation"><select className="h-12 w-full rounded-xl border bg-background px-3" value={f.permission_id} onChange={x=>setF(v=>({...v,permission_id:x.target.value}))} required><option value="">Sélectionner</option>{p.map(x=><option key={x.id} value={x.id}>{x.module} · {x.libelle}</option>)}</select></Field><Field label="Affectation concernée"><select className="h-12 w-full rounded-xl border bg-background px-3" value={f.affectation_acteur_id} onChange={x=>setF(v=>({...v,affectation_acteur_id:x.target.value}))}><option value="">Aucune affectation précise</option>{a.map(x=><option key={x.id} value={x.id}>{x.acteur.nom_complet} · {x.niveau_affectation}</option>)}</select></Field><Field label="Justification"><textarea className="min-h-32 w-full rounded-xl border bg-background p-3" value={f.justification} onChange={x=>setF(v=>({...v,justification:x.target.value}))} required/></Field><Button>Envoyer la demande</Button></form></CardContent></Card></>}
export function PermissionRequestDetailPage(){const{id}=useParams();const[d,setD]=useState<PermissionRequest|null>(null);async function load(){if(id)setD(await accountsApi.permissionRequest(+id))}useEffect(()=>{void load()},[id]);if(!d)return<Loading/>;return <><PageHeader title={`Demande #${d.id}`} backTo="/app/permissions/demandes"/><Card><CardContent className="space-y-5 p-7"><p><b>Demandeur :</b> {d.acteur.nom_complet}</p><p><b>Autorisation :</b> {d.permission.libelle}</p><p><b>Justification :</b> {d.justification}</p><p><b>Statut :</b> <StatusBadge value={d.statut}/></p>{d.motif_decision&&<p><b>Décision :</b> {d.motif_decision}</p>}</CardContent></Card>{d.statut==='en_attente'&&<div className="mt-5 flex gap-3"><PermissionGuard permission={P.APPROVE_PERMISSION_REQUEST}><Button onClick={async()=>{await accountsApi.approvePermissionRequest(d.id,{});await load()}}>Accepter</Button></PermissionGuard><PermissionGuard permission={P.REJECT_PERMISSION_REQUEST}><Button variant="destructive" onClick={async()=>{await accountsApi.rejectPermissionRequest(d.id,{motif_decision:'Demande refusée.'});await load()}}>Refuser</Button></PermissionGuard></div>}</>}

export function DelegationsListPage(){const[r,setR]=useState<Delegation[]>([]);useEffect(()=>{accountsApi.delegations().then(setR)},[]);return <><PageHeader title="Délégations" actionTo="/app/delegations/nouvelle" actionLabel="Créer une délégation"/>{r.length===0?<EmptyState message="Aucune délégation."/>:<Card><Table><TableHeader><TableRow><TableHead>Source</TableHead><TableHead>Cible</TableHead><TableHead>Objet</TableHead><TableHead>Fin</TableHead><TableHead>Statut</TableHead><TableHead/></TableRow></TableHeader><TableBody>{r.map(x=><TableRow key={x.id}><TableCell>{x.acteur_source.nom_complet}</TableCell><TableCell>{x.acteur_cible.nom_complet}</TableCell><TableCell>{x.role?.libelle||x.permission?.libelle||x.type_delegation}</TableCell><TableCell>{x.date_fin}</TableCell><TableCell><StatusBadge value={x.statut}/></TableCell><TableCell><Button render={<Link to={`/app/delegations/${x.id}`}/>} variant="outline" size="sm">Voir</Button></TableCell></TableRow>)}</TableBody></Table></Card>}</>}
export function DelegationCreatePage(){const nav=useNavigate();const[actors,setActors]=useState<Actor[]>([]);const[assignments,setAssignments]=useState<ActorAssignment[]>([]);const[roles,setRoles]=useState<Role[]>([]);const[perms,setPerms]=useState<Permission[]>([]);const[f,setF]=useState({acteur_source_id:'',acteur_cible_id:'',affectation_acteur_id:'',type_delegation:'permission',role_id:'',permission_id:'',date_fin:'',motif:''});useEffect(()=>{accountsApi.actors().then(setActors);accountsApi.assignments().then(setAssignments);accountsApi.roles().then(setRoles);accountsApi.permissions().then(setPerms)},[]);async function submit(x:React.FormEvent){x.preventDefault();const d=await accountsApi.createDelegation({...f,acteur_source_id:+f.acteur_source_id,acteur_cible_id:+f.acteur_cible_id,affectation_acteur_id:+f.affectation_acteur_id,role_id:f.type_delegation==='role'?+f.role_id:null,permission_id:f.type_delegation==='permission'?+f.permission_id:null});nav(`/app/delegations/${d.id}`)}return <><PageHeader title="Créer une délégation" backTo="/app/delegations"/><Card><CardContent className="p-7"><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Select label="Acteur source" value={f.acteur_source_id} set={v=>setF(x=>({...x,acteur_source_id:v}))} options={actors.map(a=>[String(a.id),a.nom_complet])}/><Select label="Acteur cible" value={f.acteur_cible_id} set={v=>setF(x=>({...x,acteur_cible_id:v}))} options={actors.map(a=>[String(a.id),a.nom_complet])}/><Select label="Affectation" value={f.affectation_acteur_id} set={v=>setF(x=>({...x,affectation_acteur_id:v}))} options={assignments.map(a=>[String(a.id),`${a.acteur.nom_complet} · ${a.niveau_affectation}`])}/><Select label="Type" value={f.type_delegation} set={v=>setF(x=>({...x,type_delegation:v}))} options={[['permission','Permission'],['role','Rôle']]}/>{f.type_delegation==='role'?<Select label="Rôle" value={f.role_id} set={v=>setF(x=>({...x,role_id:v}))} options={roles.map(r=>[String(r.id),r.libelle])}/>:<Select label="Permission" value={f.permission_id} set={v=>setF(x=>({...x,permission_id:v}))} options={perms.map(p=>[String(p.id),p.libelle])}/>}<Field label="Date de fin"><Input type="date" value={f.date_fin} onChange={x=>setF(v=>({...v,date_fin:x.target.value}))} required/></Field><Field label="Motif"><Input value={f.motif} onChange={x=>setF(v=>({...v,motif:x.target.value}))}/></Field><div className="sm:col-span-2"><Button>Créer la délégation</Button></div></form></CardContent></Card></>}
export function DelegationDetailPage(){const{id}=useParams();const[d,setD]=useState<Delegation|null>(null);async function load(){if(id)setD(await accountsApi.delegation(+id))}useEffect(()=>{void load()},[id]);if(!d)return<Loading/>;return <><PageHeader title={`Délégation #${d.id}`} backTo="/app/delegations"/><Card><CardContent className="grid gap-6 p-7 sm:grid-cols-2">{Object.entries({Source:d.acteur_source.nom_complet,Cible:d.acteur_cible.nom_complet,Type:d.type_delegation,Objet:d.role?.libelle||d.permission?.libelle||'—',Début:d.date_debut,Fin:d.date_fin,Motif:d.motif||'—',Statut:d.statut}).map(([k,v])=><div key={k}><p className="text-sm text-muted-foreground">{k}</p><p className="font-semibold">{v}</p></div>)}</CardContent></Card>{d.est_active&&<PermissionGuard permission={P.END_DELEGATION}><Button className="mt-5" variant="destructive" onClick={async()=>{await accountsApi.endDelegation(d.id);await load()}}>Terminer la délégation</Button></PermissionGuard>}</>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[][]}){return <Field label={label}><select className="h-12 w-full rounded-xl border bg-background px-3" value={value} onChange={x=>set(x.target.value)} required><option value="">Sélectionner</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>}
