export const IMPORT_PERMISSIONS = {
  CREATE: "creer_import_officiel",
  LIST: "lister_imports_officiels",
  VIEW: "consulter_import_officiel",
  UPDATE: "modifier_import_officiel",
  DELETE: "supprimer_import_officiel",
  EXPECTED_FIELDS: "consulter_champs_attendus_import",
  PROGRESS: "consulter_progression_import",
  RETRY_READ: "relancer_lecture_import",
  VALIDATE_MAPPING: "valider_correspondance_import",
  VALIDATE_ROWS: "valider_lignes_import",
  CONFIRM: "confirmer_import_officiel",
  CANCEL: "annuler_import_officiel",
  VIEW_MAPPINGS: "consulter_correspondances_import",
  VIEW_ROWS: "consulter_lignes_import",
  FIX_ROW: "corriger_ligne_import",
  IGNORE_ROW: "ignorer_ligne_import",
  VIEW_ERRORS: "consulter_erreurs_import",
} as const
