import { ORGANISATION_PERMISSIONS as P } from "./permissions"

export const ORGANISATION_GROUPS = {
  HOSTING: [
    P.VIEW_HOSTING,
    P.CREATE_DORMITORY,
    P.UPDATE_DORMITORY,
    P.DISABLE_DORMITORY,
    P.MAINTAIN_DORMITORY,
    P.CREATE_BED,
    P.UPDATE_BED,
    P.MAINTAIN_BED,
    P.ENABLE_BED,
  ],
  DORMITORIES: [P.VIEW_HOSTING, P.CREATE_DORMITORY, P.UPDATE_DORMITORY, P.DISABLE_DORMITORY, P.MAINTAIN_DORMITORY],
  BEDS: [P.VIEW_HOSTING, P.CREATE_BED, P.UPDATE_BED, P.MAINTAIN_BED, P.ENABLE_BED],
  CENTER_ORGANIZATION: [
    P.VIEW_CENTER_RULES,
    P.CONFIGURE_CENTER_RULES,
    P.UPDATE_CENTER_RULES,
    P.GENERATE_STRUCTURES,
    P.VALIDATE_CENTER_ORGANIZATION,
    P.MARK_CENTER_READY,
  ],
  INTERNAL_DISTRIBUTION: [
    P.VIEW_CENTER_RULES,
    P.GENERATE_STRUCTURES,
    P.CREATE_SECTION,
    P.UPDATE_SECTION,
    P.CREATE_GROUP,
    P.UPDATE_GROUP,
    P.ASSIGN_GROUP,
    P.VIEW_HOSTING,
    P.PROPOSE_BED,
    P.ASSIGN_BED,
  ],
} as const
