export const ORGANISATION_PERMISSIONS = {
  CREATE_DORMITORY: "creer_dortoir",
  UPDATE_DORMITORY: "modifier_dortoir",
  DISABLE_DORMITORY: "desactiver_dortoir",
  MAINTAIN_DORMITORY: "mettre_dortoir_hors_service",
  CREATE_BED: "creer_lit",
  UPDATE_BED: "modifier_lit",
  MAINTAIN_BED: "mettre_lit_hors_service",
  ENABLE_BED: "reactiver_lit",
  VIEW_HOSTING: "consulter_hebergement",
  VIEW_CENTER_RULES: "consulter_regles_centre",
  CONFIGURE_CENTER_RULES: "configurer_regles_centre",
  UPDATE_CENTER_RULES: "modifier_regles_centre",
  GENERATE_STRUCTURES: "generer_sections_groupes",
  VALIDATE_CENTER_ORGANIZATION: "valider_organisation_interne",
  MARK_CENTER_READY: "marquer_centre_pret_publication",
  CREATE_SECTION: "creer_section",
  UPDATE_SECTION: "modifier_section",
  DELETE_SECTION: "supprimer_section",
  CREATE_GROUP: "creer_groupe",
  UPDATE_GROUP: "modifier_groupe",
  DELETE_GROUP: "supprimer_groupe",
  ASSIGN_GROUP: "affecter_immerge_groupe",
  REMOVE_GROUP: "retirer_immerge_groupe",
  ASSIGN_BED: "attribuer_lit",
  PROPOSE_BED: "proposer_attribution_lit",
  UPDATE_BED_ASSIGNMENT: "modifier_attribution_lit",
  RELEASE_BED: "liberer_lit",
} as const

export type OrganisationPermission = typeof ORGANISATION_PERMISSIONS[keyof typeof ORGANISATION_PERMISSIONS]
