import { ACCOUNT_PERMISSIONS as P } from "./permissions"

export const ACCOUNT_GROUPS = {
  ACTORS: [P.LIST_ACTORS, P.VIEW_ACTOR, P.CREATE_ACTOR, P.UPDATE_ACTOR, P.DISABLE_ACTOR, P.ENABLE_ACTOR],
  ASSIGNMENTS: [P.ASSIGN_ACTOR, P.REMOVE_ACTOR_ASSIGNMENT, P.SUSPEND_ACTOR_ASSIGNMENT, P.ENABLE_ACTOR_ASSIGNMENT, P.ASSIGN_ROLE, P.REMOVE_ROLE, P.ASSIGN_DIRECT_PERMISSION, P.REMOVE_DIRECT_PERMISSION],
  ROLES: [P.LIST_ROLES, P.VIEW_ROLE, P.CREATE_ROLE, P.UPDATE_ROLE, P.DISABLE_ROLE, P.ADD_ROLE_PERMISSION, P.REMOVE_ROLE_PERMISSION],
  PERMISSIONS: [P.LIST_PERMISSIONS, P.VIEW_PERMISSION, P.ADD_ROLE_PERMISSION, P.REMOVE_ROLE_PERMISSION, P.ASSIGN_DIRECT_PERMISSION, P.REMOVE_DIRECT_PERMISSION, P.REQUEST_PERMISSION, P.LIST_PERMISSION_REQUESTS, P.VIEW_PERMISSION_REQUEST, P.APPROVE_PERMISSION_REQUEST, P.REJECT_PERMISSION_REQUEST],
  REQUESTS: [P.REQUEST_PERMISSION, P.LIST_PERMISSION_REQUESTS, P.VIEW_PERMISSION_REQUEST, P.APPROVE_PERMISSION_REQUEST, P.REJECT_PERMISSION_REQUEST],
} as const
