export const ACCOUNT_PERMISSIONS = {
  CHOOSE_CONTEXT: "choisir_contexte",
  CHANGE_PASSWORD: "changer_mot_de_passe",
  VIEW_PROFILE: "consulter_profil",
  UPDATE_PROFILE: "modifier_profil",
  CREATE_ACTOR: "creer_acteur",
  UPDATE_ACTOR: "modifier_acteur",
  DISABLE_ACTOR: "desactiver_acteur",
  ENABLE_ACTOR: "reactiver_acteur",
  VIEW_ACTOR: "consulter_acteur",
  LIST_ACTORS: "lister_acteurs",
  ASSIGN_ACTOR: "affecter_acteur_session",
  REMOVE_ACTOR_ASSIGNMENT: "retirer_affectation_acteur",
  SUSPEND_ACTOR_ASSIGNMENT: "suspendre_affectation_acteur",
  ENABLE_ACTOR_ASSIGNMENT: "reactiver_affectation_acteur",
  CREATE_ROLE: "creer_role",
  UPDATE_ROLE: "modifier_role",
  DISABLE_ROLE: "desactiver_role",
  VIEW_ROLE: "consulter_role",
  LIST_ROLES: "lister_roles",
  ASSIGN_ROLE: "attribuer_role",
  REMOVE_ROLE: "retirer_role",
  VIEW_PERMISSION: "consulter_permission",
  LIST_PERMISSIONS: "lister_permissions",
  ADD_ROLE_PERMISSION: "ajouter_permission_role",
  REMOVE_ROLE_PERMISSION: "retirer_permission_role",
  ASSIGN_DIRECT_PERMISSION: "attribuer_permission_directe",
  REMOVE_DIRECT_PERMISSION: "retirer_permission_directe",
  REQUEST_PERMISSION: "demander_permission",
  LIST_PERMISSION_REQUESTS: "lister_demandes_permissions",
  VIEW_PERMISSION_REQUEST: "consulter_demande_permission",
  APPROVE_PERMISSION_REQUEST: "approuver_demande_permission",
  REJECT_PERMISSION_REQUEST: "refuser_demande_permission",
  CREATE_DELEGATION: "creer_delegation",
  END_DELEGATION: "terminer_delegation",
  LIST_DELEGATIONS: "lister_delegations",
  VIEW_DELEGATION: "consulter_delegation",
} as const

export type AccountPermission = typeof ACCOUNT_PERMISSIONS[keyof typeof ACCOUNT_PERMISSIONS]
